<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ContainerRuntimeIdentifier>win-x64</ContainerRuntimeIdentifier>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0-nanoserver-ltsc2022</ContainerBaseImage>
    <UserSecretsId>b8851930-2bdd-490f-92f0-c7a3c04855ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

</Project>
